data<-read.table('household_power_consumption.txt',header=T,sep=';')
data$date.time<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
data1<-subset(data,data$date.time<'2007-02-03' & data$date.time>='2007-02-01')
data1$Global_active_power<-as.numeric(as.character(data1$Global_active_power))
data1$Sub_metering_1<-as.numeric(as.character(data1$Sub_metering_1))
data1$Sub_metering_2<-as.numeric(as.character(data1$Sub_metering_2))
data1$Sub_metering_3<-as.numeric(as.character(data1$Sub_metering_3))
windows()
with(data1,plot(date.time,Sub_metering_1,type='l',ylab="Energy sub metering",xlab=''))
     lines(data1$date.time,data1$Sub_metering_2,col="red")
     lines(data1$date.time,data1$Sub_metering_3,col="blue")   
     legend("topright",lty=1,col=c("black","red","blue"),legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
dev.copy(png, file = "plot3.png") 
dev.off() 