data<-read.table('household_power_consumption.txt',header=T,sep=';')
data$date.time<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
data1<-subset(data,data$date.time<'2007-02-03' & data$date.time>='2007-02-01')
data1$Global_active_power<-as.numeric(as.character(data1$Global_active_power))
windows()
with(data1,plot(date.time,Global_active_power,type='l',ylab="Global active power (kilowatts)",xlab=''))
dev.copy(png, file = "plot2.png") 
dev.off() 